const menu = [
  {
    id: 1,
    title: 'Snow Latte Mide Chair',
    desc: 'The Mide Chair combines modern design with exceptional comfort, With its sleek lines and ergonomic support, this chair is designed to enhance your seating experience.',
    price: 100.0,
    reviews: '10k+ Reviews',
    image: '/images/image-1.png',
  },
  {
    id: 2,
    title: 'Marshmallow Mide Bar stool',
    desc: 'The Marshmallow Mide Bar Chair is the epitome of elegance and comfort, designed to bring a touch of sophistication to any bar or kitchen counter.',
    price: 170.0,
    reviews: '10k+ Reviews',
    image: '/images/image-2.png',
  },
  {
    id: 3,
    title: 'Gymax Adjustable Mide Chair',
    desc: 'The Gymax Adjustable Mide Chair offers a perfect blend of modern design and versatile functionality, ideal for any workspace or home office.',
    price: 180.0,
    reviews: '10k+ Reviews',
    image: '/images/image-3.png',
  },
  {
    id: 4,
    title: 'Hector Velvet Mide Chair',
    desc: 'The Hector Velvet Mide Chair combines luxurious comfort with timeless elegance, making it a standout piece in any room. this chair provides a plush seating experience while exuding sophistication.',
    price: 100.0,
    reviews: '10k+ Reviews',
    image: '/images/image-4.png',
  },
  {
    id: 5,
    title: 'Nordic Minimalistic Mide Chair',
    desc: 'The Nordic Minimalistic Mide Chair is the epitome of Scandinavian design, offering a sleek and stylish seating solution that complements any modern interior.',
    price: 100.0,
    reviews: '10k+ Reviews',
    image: '/images/image-5.png',
  },
  {
    id: 6,
    title: 'Vintage Ivory Mide Chair',
    desc: 'The Vintage Ivory Mide Chair exudes classic elegance and timeless charm, making it a perfect addition to any sophisticated interior. With its beautifully crafted details and luxurious comfort.',
    price: 145.0,
    reviews: '10k+ Reviews',
    image: '/images/image-6.png',
  },
  {
    id: 7,
    title: 'Red oval Mide Chair',
    desc: 'The Red Oval Mide Chair is a stunning blend of contemporary design and exceptional comfort. Its bold color and unique oval shape  offering both visual appeal and practical seating.',
    price: 260.0,
    reviews: '10k+ Reviews',
    image: '/images/image-7.png',
  },
  {
    id: 8,
    title: 'Hayneedle Mide Chair',
    desc: 'The Hayneedle Mide Chair brings a touch of classic elegance and modern functionality to any space. With its sophisticated design and high-quality craftsmanship, making it perfect addition to your home.',
    price: 200.0,
    reviews: '10k+ Reviews',
    image: '/images/image-8.png',
  },
  {
    id: 9,
    title: 'Waffle Mide Chair',
    desc: 'The Waffle Mide Chair combines contemporary design with exceptional comfort, making it an ideal choice for modern interiors. With its unique waffle-patterned, this chair offer style and support.',
    price: 200.0,
    reviews: '10k+ Reviews',
    image: '/images/image-9.png',
  },
  {
    id: 10,
    title: 'Sejour Mide Chair',
    desc: 'The Sejour Mide Chair blends timeless elegance with modern comfort, making it a standout piece for any interior. This chair offers a luxurious seating experience that complements a variety of decor styles.',
    price: 700.0,
    reviews: '10k+ Reviews',
    image: '/images/image-10.png',
  },
  {
    id: 11,
    title: 'Ochre arm Mide Chair',
    desc: 'The Ochre Arm Mide Chair brings a touch of modern sophistication to any space with its bold color and sleek design. Featuring comfortable armrests this chair is designed to offer both style and support.',
    price: 400.0,
    reviews: '10k+ Reviews',
    image: '/images/image-11.png',
  },
  {
    id: 12,
    title: 'Galerie Mide Chair',
    desc: 'The Galerie Mide Chair combines artistic flair with modern comfort, making it a perfect centerpiece for any stylish interior. this chair offers a unique seating experience that is functional and visually appealing.',
    price: 450.0,
    reviews: '10k+ Reviews',
    image: '/images/image-12.png',
  },
];

export default menu;

export const cart = [
  {
    id: 1,
    image: '/images/image 10.png',
    title: 'Red oval Mide Chair',
    price: '$520.00',
    quantity: 2,
    color: '/images/color1.svg',
  },
  {
    id: 2,
    image: '/images/image-4.png',
    title: 'Hector Velvet Mide Chair',
    price: '$200.00',
    quantity: 1,
    color: '/images/color2.svg',
  },
  {
    id: 3,
    image: '/images/image-11.png',
    title: 'Ochre arm Mide Chair',
    price: '$400.00',
    quantity: 1,
    color: '/images/color3.svg',
  },
];
